export const actionTypes = {
  SET_IS_SELECTED_BIRD_EXIST: "IS_SELECTED_BIRD_EXIST",
  SET_SELECTED_BIRD: "SET_SELECTED_BIRD",
  SET_IS_CORRECT_CURRENT_BIRD: "IS_CORRECT_CURRENT_BIRD",
  SET_LEVEL: "SET_LEVEL",
  SET_TOTAL_SCORE: "SET_TOTAL_SCORE",
  RESET_TOTAL_SCORE: "RESET_TOTAL_SCORE",
  SET_SCORE_ON_THE_LEVEL: "SET_SCORE_ON_THE_LEVEL",
  SET_IS_LEVEL_COMPLETED: "IS_LEVEL_COMPLETED",
};
