const IS_SELECTED_BIRD_EXIST = "IS_SELECTED_BIRD_EXIST";
const SET_SELECTED_BIRD = "SET_SELECTED_BIRD";
const IS_CORRECT_CURRENT_BIRD = "IS_CORRECT_CURRENT_BIRD";

export const actionTypes = {
  SET_IS_SELECTED_BIRD_EXIST: IS_SELECTED_BIRD_EXIST,
  SET_SELECTED_BIRD: SET_SELECTED_BIRD,
  SET_IS_CORRECT_CURRENT_BIRD: IS_CORRECT_CURRENT_BIRD,
};
